apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: employee-service
build:
  artifacts:
    - image: pjaiswal/employee
      jib:
        args:
          - -DskipTests
  tagPolicy:
    gitCommit: {}
manifests:
  rawYaml:
    - ../k8s/privileges.yaml
    - ../k8s/mongodb-**.yaml
    - k8s/**.yaml
