apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: gateway-service
build:
  artifacts:
    - image: pjaiswal/gateway
      jib: {}
  tagPolicy:
    gitCommit: {}
manifests:
  rawYaml:
    - ../k8s/privileges.yaml
    - k8s/**.yaml
